local map = function(mode, lhs, rhs, desc)
  vim.keymap.set(mode, lhs, rhs, { buffer = true, desc = desc })
end

map("n", "<leader>co", function()
  require("jdtls").organize_imports()
end, "Organize Imports")
map("n", "<leader>crv", function()
  require("jdtls").extract_variable()
end, "Extract Variable")
map("v", "<leader>crv", function()
  require("jdtls").extract_variable(true)
end, "Extract Variable")
map("n", "<leader>crc", function()
  require("jdtls").extract_constant()
end, "Extract Constant")
map("v", "<leader>crc", function()
  require("jdtls").extract_constant(true)
end, "Extract Constant")
map("v", "<leader>crm", function()
  require("jdtls").extract_method(true)
end, "Extract Method")
map("n", "<leader>Jt", function()
  require("jdtls").test_nearest_method()
end, "[J]ava [T]est Method")
map("v", "<leader>Jt", function()
  require("jdtls").test_nearest_method(true)
end, "[J]ava [T]est Method")
map("n", "<leader>JT", function()
  require("jdtls").test_class()
end, "[J]ava [T]est Class")
map("n", "<leader>Ju", "<Cmd>JdtUpdateConfig<CR>", "[J]ava [U]pdate Config")
